---
- name: Configures Appsec in vmware Esxi
  hosts: all

  vars_files:
    - variables.yml
 
  tasks:
    - name: Removing node_id.txt
      become: yes
      file:
        path: /etc/portmanager/node_id.txt
        state: absent

    - name: Configuring Node (updating Controller IP, test and Management interface)
      become: yes
      shell: |
        sudo cyperfagent controller set {{ VarNatsBrokerUrl }}
        sudo cyperfagent interface test set ${{ VarTestInterface }}
        sudo cyperfagent interface management set {{ VarManagementInterface }}
      args:
        executable: /bin/bash